// https://nextui.org/docs/components

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ModalScanner from '../comps/ModalScanner'
import { Collapse, Grid, Text, Textarea, Card, Container, Row, Col } from '@nextui-org/react';
import React from 'react'

const fetcher = (url) => fetch(url).then(res => res.json())

export default function Home() {
  const [materials, setMaterials] = React.useState([])

  return (
    <div className={styles.container}>
      <Head>
        <title>Dow Track Pack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Dow Track Pack
        </h3>

        <ModalScanner
          materials={materials}
          setMaterials={setMaterials}
        />

        <Collapse.Group>
          <Collapse title="Polymer">
            <Collapse.Group>
              <Collapse title="General">
                <Textarea
                  readOnly
                  label="Batch Id"
                  initialValue="3855932"
                  placeholder="N/A"
                  minRows={1}
                  width={'100%'}
                />
                <Grid.Container gap={1.5} justify="center">
                  <Grid xs={6}>
                    <Textarea
                      readOnly
                      label="Material Id"
                      placeholder="N/A"
                      initialValue="2371904"
                      minRows={1}
                      width={'100%'}
                    />
                  </Grid>
                  <Grid xs={6}>
                    <Textarea
                      readOnly
                      label="Material Name"
                      placeholder="N/A"
                      initialValue="HDBP"
                      minRows={1}
                      width={'100%'}
                    />
                  </Grid>
                </Grid.Container>
                <Grid.Container gap={1.5}>
                  <Grid xs={4}>
                    <Textarea
                      readOnly
                      label="Customer Id"
                      initialValue="9705972"
                      placeholder="N/A"
                      minRows={1}
                      width={'100%'}
                    />
                  </Grid>
                  <Grid xs={8}>
                    <Textarea
                      readOnly
                      label="Customer"
                      initialValue="9705972"
                      placeholder="N/A"
                      minRows={1}
                      width={'100%'}
                    />
                  </Grid>
                </Grid.Container>
                <Textarea
                  readOnly
                  label="Site Created"
                  initialValue="3475 E North Union Rd, Bay City, MI 48706"
                  placeholder="3475 E North Union Rd, Bay City, MI 48706"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Quantity"
                  placeholder="0"
                  initialValue="200mt"
                  minRows={1}
                  width={'100%'}
                />
              </Collapse>
            </Collapse.Group>

            {/* Transit Info */}
            <Collapse.Group>
              <Collapse title="Transit Info">
                <Textarea
                  readOnly
                  label="Transit Id"
                  placeholder="N/A"
                  initialValue="3829372"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Date & Time Departure"
                  placeholder="N/A"
                  initialValue="03:10:29 10/08/2022 GMT"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Date & Time Received"
                  placeholder="N/A"
                  initialValue="07:13:29 10/08/2022 GMT"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Delivered From"
                  placeholder="N/A"
                  initialValue="3475 E North Union Rd, Bay City, MI 48706"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Delivered To"
                  placeholder="N/A"
                  initialValue="3475 E North Union Rd, Bay City, MI 48706"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Transit Type"
                  placeholder="N/A"
                  initialValue="Truck"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Arrived"
                  placeholder="No"
                  initialValue="Yes"
                  minRows={1}
                  width={'100%'}
                />
              </Collapse>
            </Collapse.Group>

            {/* Sustainability Metrics */}
            <Collapse.Group>
              <Collapse title="Sustainability Metrics">
                <Textarea
                  readOnly
                  label="Carbon Emission"
                  placeholder="0"
                  initialValue="20mt"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Quantity"
                  placeholder="0"
                  initialValue="N/A"
                  minRows={1}
                  width={'100%'}
                />
                <Textarea
                  readOnly
                  label="Electricity Used"
                  placeholder="0"
                  initialValue="200mw"
                  minRows={1}
                  width={'100%'}
                />
                <Text>Waste...</Text>
              </Collapse>
            </Collapse.Group>

            {/* Raw Materials */}
            <Collapse.Group>
              <Collapse title="Raw Materials">
                <Text>Materials</Text>
                <Text>Bun</Text>
                <Text>Pickles</Text>
                <Text>Lettuce</Text>
                <Text>Bacon</Text>
                <Text>Ham</Text>
                <Text>Bun</Text>
              </Collapse>
            </Collapse.Group>

          </Collapse>
        </Collapse.Group>

        <Collapse.Group>
          {
            materials.map(value => {
              return (
                <Collapse title={'Item: ' + value} key={value}>
                  <Text>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                    minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat.
                  </Text>
                  <Textarea
                    label="asdasd"
                    placeholder="asdas"
                  />
                </Collapse>
              )
            })
          }
        </Collapse.Group>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
