// https://nextui.org/docs/components

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ModalScanner from '../comps/ModalScanner'
import { Collapse, Text } from '@nextui-org/react';
import React from 'react'

export default function Home() {
  const [materials, setMaterials] = React.useState([])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dow Track Pack
        </h1>

        

        <ModalScanner
          materials={materials}
          setMaterials={setMaterials}
        />

        <Collapse.Group>
        {
          materials.map(value => {
            return (
              <Collapse title={'Item: ' + value} key={value}>
                <Text>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                  minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                  aliquip ex ea commodo consequat.
                </Text>
              </Collapse>
            )
          })
        }
        </Collapse.Group>      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
