// https://nextui.org/docs/components

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ModalScanner from '../comps/ModalScanner'
import { Collapse, Grid, Text, Textarea, Spacer } from '@nextui-org/react';
import React, { useEffect } from 'react'
import { animated, useSpring } from '@react-spring/web'
import CustomTitle from '../comps/CustomTitle/CustomTitle'
import CustomEpicHeader from '../comps/CustomEpicHeader';
import CustomTamedHeader from '../comps/CustomTamedHeader';
import TrackingBody from '../comps/TrackingBody';

const getData = () => {
  return ([
    {
      "batchId": "0123456",
      "materialId": "2523513",
      "customerId": "5253241",
      "siteCreated": "3475 E North Union Rd, Bay City, MI 48706",
      "quantity": 20,
      "transits": [
        {
          "transitId": "352351",
          "dateTimeDeparture": "10:45:00 10/08/2022",
          "dateTimeReceived": "12:45:00 10/08/2022",
          "deliveredFrom": "3475 E North Union Rd, Bay City, MI 48706",
          "deliveredTo": "3475 E North Union Rd, Bay City, MI 48706",
          "transitType": "Train",
          "arrived": true
        },
        {
          "transitId": "235235",
          "dateTimeDeparture": "10:45:00 10/08/2022",
          "dateTimeReceived": "12:45:00 10/08/2022",
          "deliveredFrom": "3475 E North Union Rd, Bay City, MI 48706",
          "deliveredTo": "3475 E North Union Rd, Bay City, MI 48706",
          "transitType": "Train",
          "arrived": true
        },
        {
          "transitId": "325325",
          "dateTimeDeparture": "10:45:00 10/08/2022",
          "dateTimeReceived": "12:45:00 10/08/2022",
          "deliveredFrom": "3475 E North Union Rd, Bay City, MI 48706",
          "deliveredTo": "3475 E North Union Rd, Bay City, MI 48706",
          "transitType": "Train",
          "arrived": true
        }
      ],
      "sustainabilityMetrics": {
        "carbonEmission": 30,
        "electricityUsed": 20,
        "waterUsed": 10,
        "waste": [
          "Something",
          "Something Else",
          "Something More"
        ]
      },
      "rawMaterials": [
        "Something",
        "Something Else",
        "Something More"
      ]
    },
    {
      "batchId": "6543210",
      "materialId": "2523513",
      "customerId": "5253241",
      "siteCreated": "3475 E North Union Rd, Bay City, MI 48706",
      "quantity": 20,
      "transits": [
        {
          "transitId": "352351",
          "dateTimeDeparture": "10:45:00 10/08/2022",
          "dateTimeReceived": "12:45:00 10/08/2022",
          "deliveredFrom": "3475 E North Union Rd, Bay City, MI 48706",
          "deliveredTo": "3475 E North Union Rd, Bay City, MI 48706",
          "transitType": "Train",
          "arrived": true
        },
        {
          "transitId": "235235",
          "dateTimeDeparture": "10:45:00 10/08/2022",
          "dateTimeReceived": "12:45:00 10/08/2022",
          "deliveredFrom": "3475 E North Union Rd, Bay City, MI 48706",
          "deliveredTo": "3475 E North Union Rd, Bay City, MI 48706",
          "transitType": "Train",
          "arrived": true
        },
        {
          "transitId": "325325",
          "dateTimeDeparture": "10:45:00 10/08/2022",
          "dateTimeReceived": "12:45:00 10/08/2022",
          "deliveredFrom": "3475 E North Union Rd, Bay City, MI 48706",
          "deliveredTo": "3475 E North Union Rd, Bay City, MI 48706",
          "transitType": "Train",
          "arrived": true
        }
      ],
      "sustainabilityMetrics": {
        "carbonEmission": 30,
        "electricityUsed": 20,
        "waterUsed": 10,
        "waste": [
          "Something",
          "Something Else",
          "Something More"
        ]
      },
      "rawMaterials": [
        "Something",
        "Something Else",
        "Something Less"
      ]
    }
  ])
}

export default function Home() {
  const [materials, setMaterials] = React.useState(new Map())
  // remove default value for anything other than ui testing/dev
  const [currentMaterial, setCurrentMaterial] = React.useState(null)
  //const [currentMaterial, setCurrentMaterial] = React.useState(getData()[0])

  const handleMaterialScanned = (text) => {
    if (!materials.has(text)) {
      // Find current material from example data and set
      const mat = getData().find(batch => batch.batchId == text)
      setMaterials(materials.set(text, mat))
      setCurrentMaterial(mat)
    } else {
      console.log(materials.get(text))
      setCurrentMaterial(materials.get(text))
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Dow Tracking System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {currentMaterial !== null ?
          // ALREADY SCANNED BATCH
          <CustomTamedHeader
            materials={materials}
            handleMaterialScanned={handleMaterialScanned}
          /> :
          // BATCH HAS NOT BEEN SCANNED
          <CustomEpicHeader
            materials={materials}
            handleMaterialScanned={handleMaterialScanned}
          />
        }

        <div className={styles.content}>
          {currentMaterial != null &&
            <TrackingBody
              currentMaterial={currentMaterial}
            />
          }
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}